### ISSUE TITLE
Some hardcoded assets

### ISSUE THREAD

**Issue by danipen** [hez2010/VolumeRenderer#2]
Hi, I'm exploring this sample but not working for me. Here it seems there are some hardocded paths to assets: https://github.com/hez2010/VolumeRenderer/blob/0a90e9d68fb33724c781d4a273dcb9d615eef547/VolumeRendererControl.cs#L293

**Comment by hez2010** [comment]
Hi! Thanks for pointing out.
I've pushed a new commit to address the issue. Please check again.

**Comment by danipen** [comment]
Awesome thanks!

**Comment by hez2010** [comment]
Closing as resolved.
